services:
  backend:
    image: lukabratzee/video-game-catalogue-backend:latest
    pull_policy: always
    platform: linux/amd64
    container_name: video-game-catalogue-backend
    ports:
      - "5002:5001"
    environment:
      - DATABASE_PATH=/app/data/games.db
      - BACKEND_PORT=5002
      - DOCKER_ENV=true
      - PYTHONUNBUFFERED=1
      - DEBUG=true
    volumes:
      - /root/docker/video-game-catalogue/data:/app/data:rw
      - /root/docker/video-game-catalogue/config:/app/config:rw
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep app.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    restart: unless-stopped

  frontend:
    image: lukabratzee/video-game-catalogue-frontend:latest
    pull_policy: always
    platform: linux/amd64
    container_name: video-game-catalogue-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=5002
      - FRONTEND_PORT=8501
    depends_on:
      backend:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    restart: unless-stopped

volumes:
  data:
    driver: local
  config:
    driver: local

networks:
  default:
    driver: bridge
