version: '3.8'

services:
  frontend: # Frontend for videogame scanner
    image: videogamescanner/frontend:latest
    container_name: videogamescanner-frontend
    restart: unless-stopped    
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - BACKEND_HOST=backend  # Use the provided IP or default to local      

  backend: # Backend for videogame scanner
    image: videogamescanner/backend:latest
    container_name: videogamescanner-backend
    restart: unless-stopped    
    volumes:
      - /root/backend/games.db:/app/games.db
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge
