version: '3'

services:
  frontend:
    build:
      context: "/root/docker/video_game_catalogue/frontend"  # Ensure absolute path
      dockerfile: Dockerfile
    container_name: videogamescanner-frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - BACKEND_HOST=backend
    volumes:
      - "/root/docker/video_game_catalogue/frontend:/app"

  backend:
    build:
      context: "/root/docker/video_game_catalogue/backend"  # Ensure absolute path
      dockerfile: Dockerfile
    container_name: videogamescanner-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network
    volumes:
      - "/root/docker/video_game_catalogue/backend:/app"
      - "/share/backup_proxmox/lukabratzee/games.db:/app/games.db"

networks:
  app-network:
    driver: bridge