version: '3'

services:
  frontend:
    image: videogamescanner/frontend:latest
    container_name: videogamescanner-frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - BACKEND_HOST=backend  # Use the service name for inter-container communication

  backend:
    image: videogamescanner/backend:latest
    container_name: videogamescanner-backend
    restart: unless-stopped
    volumes:
      - ./backend/games.db:/app/games.db  # For persistent data storage
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
