version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: videogamescanner/frontend:latest
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: videogamescanner/backend:latest
    volumes:
      - ./backend/games.db:/app/games.db
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
