version: '3'

services:
  frontend:
    # Build our Dockerfile from the 'frontend' directory
    build:
      context: "/root/docker/video_game_catalogue/frontend"
      dockerfile: Dockerfile
    container_name: videogamescanner-frontend
    restart: unless-stopped

    # Expose Streamlit on port 8501
    ports:
      - "8501:8501"

    # This container relies on 'backend' being ready first
    depends_on:
      - backend

    # Networking
    networks:
      - app-network

    # Pass environment variables to the container
    environment:
      - BACKEND_HOST=backend

    # **Key volume**: mounting /app from the host
    # Because our venv is at /venv, it isn't overwritten
    volumes:
      - "/root/docker/video_game_catalogue/frontend:/app"

  backend:
    build:
      context: "/root/docker/video_game_catalogue/backend"
      dockerfile: Dockerfile
    container_name: videogamescanner-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network
    volumes:
      # Mount backend code for live dev
      - "/root/docker/video_game_catalogue/backend:/app"
      # Mount your database file from the host
      - "/share/backup_proxmox/lukabratzee/games.db:/app/games.db"

networks:
  app-network:
    driver: bridge