services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: videogamescanner-frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - BACKEND_HOST=backend
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER_BIN=/usr/local/bin/chromedriver
      # Complete X11 isolation
      - XAUTHORITY=/tmp/.docker.xauth
      - WAYLAND_DISPLAY=""
      - XDG_SESSION_TYPE=""
      - XDG_RUNTIME_DIR=/tmp
      # Block any host display access
      - CHROME_NO_SANDBOX=true
      - CHROME_DISABLE_GPU=true
    volumes:
      - ./frontend:/app
      - ./modules:/app/modules
      # Prevent X11 forwarding by not mounting host X11 socket
    security_opt:
      - seccomp:unconfined
      - no-new-privileges:true
    # Completely isolate from host display system
    tmpfs:
      - /tmp:noexec,nosuid,size=2g
      - /dev/shm:rw,nosuid,nodev,size=2g
    # Block access to host devices but keep essential capabilities for Chrome
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
      - SYS_CHROOT
      - SYS_ADMIN  # Needed for Chrome sandbox
    read_only: false
    # Prevent mounting host filesystem
    user: root

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: videogamescanner-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER_BIN=/usr/local/bin/chromedriver
      - DATABASE_PATH=games.db
      # NUCLEAR X11 isolation - prevent ANY host display access
      - XAUTHORITY=/tmp/.docker.xauth
      - WAYLAND_DISPLAY=""
      - XDG_SESSION_TYPE=""
      - XDG_RUNTIME_DIR=/tmp
      - XORG_LOCK_DIR=/tmp
      - TMPDIR=/tmp
      - HOME=/tmp
      # Block ALL host display access
      - CHROME_NO_SANDBOX=true
      - CHROME_DISABLE_GPU=true
      # Process isolation
      - CHROME_DISABLE_X11=true
      - OZONE_PLATFORM=headless
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - ./modules:/app/modules
      - ./backend/games.db:/app/games.db
      # COMPLETELY prevent X11 forwarding - no host sockets
    security_opt:
      - seccomp:unconfined
      - no-new-privileges:true
    # NUCLEAR container isolation
    tmpfs:
      - /tmp:noexec,nosuid,size=2g
      - /dev/shm:rw,nosuid,nodev,size=2g
      - /run:rw,nosuid,nodev,size=1g
      - /var/tmp:noexec,nosuid,size=1g
    # EXTREME capability restrictions
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
      - SYS_CHROOT
      - SYS_ADMIN  # Chrome sandbox only
    read_only: false
    user: root
    # BLOCK host networking access patterns
    sysctls:
      - net.ipv4.ping_group_range=0 2147483647
    # Prevent any host process interaction
    ipc: none

networks:
  app-network:
    driver: bridge