# Docker Compose for Private GitHub Container Registry Images
# Replace 'yourusername' with your actual GitHub username

version: "3"
services:

  video-game-catalogue-backend:
    image: ghcr.io/lukabratzee/video-game-catalogue-backend:latest
    container_name: videogame-backend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - FLASK_ENV=production
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER_BIN=/usr/bin/chromedriver
      - DATABASE_PATH=/app/data/games.db  # Configurable database location
      - DOCKER_ENV=true
      - CHROME_NO_SANDBOX=true
      - CHROME_DISABLE_GPU=true
    volumes:
      - ./data:/app/data
      - ./config:/app/config  # For additional config files
    ports:
      - "5001:5001"  # Format: "HOST_PORT:CONTAINER_PORT"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:noexec,nosuid,size=1g
      - /dev/shm:rw,nosuid,nodev,size=1g
    cap_add:
      - SYS_ADMIN  # Required for Chrome sandbox
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "autoheal=true"

  video-game-catalogue-frontend:
    image: ghcr.io/lukabratzee/video-game-catalogue-frontend:latest
    container_name: videogame-frontend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - BACKEND_HOST=videogame-backend
      - BACKEND_PORT=5001
      - DISPLAY=:99
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - DOCKER_ENV=true
    ports:
      - "8501:8501"  # Format: "HOST_PORT:CONTAINER_PORT"
    depends_on:
      - video-game-catalogue-backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:noexec,nosuid,size=1g
      - /dev/shm:rw,nosuid,nodev,size=1g
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "autoheal=true"

networks:
 default:
   name: luke-docker
