version: '3.8'

services:
  frontend:
    image: videogamescanner/frontend:latest
    container_name: videogamescanner-frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_healthy  # Ensure backend is fully running before frontend starts
    networks:
      - app-network
    environment:
      - BACKEND_HOST=backend  # Use service name for inter-container communication

  backend:
    image: videogamescanner/backend:latest
    container_name: videogamescanner-backend
    restart: unless-stopped
    volumes:
      - ./backend/games.db:/app/games.db  # Persist database
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - DISPLAY=:99
    networks:
      - app-network
    shm_size: '1gb'  # Increase shared memory for Chrome stability
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge